import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthSession from "@/Providers/NextAuthSession";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Maruf Sheikh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSession>
          {children}
        </NextAuthSession>
      </body>
    </html>
  );
}
